project_name: "glucose_exporter"
builds:
  - main: ./cmd/glucose_exporter/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{.Date}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{.Tag}}-next"
source:
  format: tar.gz
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test"
      - "^ci"
      - "^lint"
      - "^build"
      - "happy linting"
      - "^chore"
      - "^style"
      - "^Revert"
release:
  github:
    owner: xsteadfastx
    name: glucose_exporter
  footer: |-
    ## docker
    `docker pull ghcr.io/xsteadfastx/glucose_exporter:{{ trimprefix .Tag "v"}}`
